name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup build system
      run: cmake .
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential libssl-dev
    - name: Setup C/C++ Compiler
      uses: rlalik/setup-cpp-compiler@v1.2
      with:
       compiler: gcc
